# Generated by Django 4.1 on 2022-08-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('tipo_prestamo', models.CharField(max_length=200)),
                ('cuotas_devolver', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_payment', models.CharField(max_length=50)),
                ('loan_date', models.CharField(max_length=50)),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes_app.cliente')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
