# Generated by Django 4.1 on 2022-08-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.CharField(max_length=200)),
                ('cuota_prestamo', models.CharField(max_length=200)),
                ('fecha_prestamo', models.CharField(max_length=200)),
                ('total_prestamo', models.CharField(max_length=200)),
                ('aPagar_prestamo', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('tipo_prestamo', models.CharField(max_length=200)),
                ('cuotas_devolver', models.CharField(max_length=200)),
            ],
        ),
    ]
