# Generated by Django 4.1 on 2022-08-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='id',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='aPagar_prestamo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuota_prestamo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='total_prestamo',
            field=models.IntegerField(),
        ),
    ]
