# Generated by Django 4.1 on 2022-08-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('tipo_tarjeta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('limite', models.IntegerField()),
                ('limite_extraccion', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('cuotas_maximas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
    ]
