# Generated by Django 4.1 on 2022-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('correo', models.DateTimeField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
